"""
This file contains the optimal constants for the trading strategy.
"""
OPTIMAL_PERIOD_FOR_RSI = 80
OPTIMAL_PERIOD_FOR_EMA = 2
TIME_FRAME = "1h"
OPTIMAL_PERIOD_FOR_MFI = 14
STOPLOSS_THRESHOLD = 0.2
OPTIMAL_POSITIVE_QUANTILE = 92.45
OPTIMAL_NEGATIVE_QUANTILE = 92.45
